name: example

on:
  release:
    types:
      - "published"

jobs:
  hoge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: test1

    steps:
      - name: Print
        run: echo "hoge"
